sudo: required
language: minimal
services:
- docker
script:
- scripts/build.sh ${TRAVIS_BRANCH} linux
- scripts/build.sh ${TRAVIS_BRANCH} darwin
deploy:
- provider: releases
  api_key:
    secure: iXduTn3Q5yp90+LHBPhJMjRTpMqEkFsYpMcBZN87yAEh8zJ20ywqQ4HlaOIOrE/pVoY5o1clW3qLSSp+V4N3rBwl5fEKif4gwZ42Cy5+hOSkteZVxz3ywZ7ftUr21TMXm36vgR603Xbx3R2Q1sjGCkKkoKW0sf9ojetvSP3Tngr20GaUaUJEO6HmwSrZgbgKl6P8Jw+2P4qTA1gB4jpazU0EbHDUc5VrQ8GNeowldrEhomQ/U8rQ5d21ot3DLJbw0/C950e9zSp7VJk7tpqJzq7fiRY8KAUQLEK6L+z76R8cG5WVD4GcCH6BgdTqToK57izNjQ0f54yvB5WDT04wlt6+PYx8H57qYCQXjXOJx5CKIJ1DFB2FzEl8VIIYf6m2jLyEAPVYcfT2hLHkPZYyYeU00aDoExVJbW36bcEXISggDX3wQtXutl+MppqNa1/NPqxCQSolEDipiahDwtTpR/66xFQdj7vwcJY7GJnBGoUUs9VArFgDTdlMpmXZh4YB1geY9RbU3D9/mQKLo5RsSC4mfk+pnLYUQ2a/TzY7lY5HfSzN1WmCfSu5FdJwbMtjkAOScQY0oa32V928TwheL5U+cSib+hOGcPYcTfpH/20MhIWarOzWf5e/A4ar3fIGjnHwfkfLc6BdsRAJK8hJAf6Nsy6NmpiO6Jucghml80A=
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: bash scripts/publish_docker.sh ${TRAVIS_BRANCH}
  on:
    tags: true
- provider: script
  script: bash scripts/publish_docker.sh ${TRAVIS_BRANCH} latest
  on:
    branch: master
env:
  global:
  - secure: m9NSYiTrfp2Ann4i1b7jnbN+Fk4GCROJUmiGkOEbpIZVxLbT2Sdte6UvAbIbO4iptVNyWY2ErwAvdrngAg+Uguaz3pt4+byV03nwtNncP6CVyD/Y1hKuq7OuMBBvdc12VZYJHweXyfG7k6oUg14zjr6ND18R0d4hUHpZk0QdlvsxbCrYdrEE2vRh9Q9lpvu8RgkcWB9tp5ZqaMTBrzRh4hbR4+0eeU/LcQ1g6OzAKYLtuoB0UehfHLjqcFKKQYYdw2QBN9CzhWdVy/uOgvwmBnZgSqc5Bnc36GCqW4SkbmGh11UZYRqDouYCjtqa3srz+vf0qTH/Q0gtTt8xezw8lP482ZG8e9pU8Hv85NhvYn3lPGF7KdMq+Z/8ng0XG6s0e9zP8lDcGMYxXAFjEKyoJ/QBgzdi4PWzuFTa9Ko2lE7jtqGaBwc4yBPjduRP7/VH/EjGq9DFEaooyH8xJPBGLB9ZJm3uZMYgagYbptNuUQfyAH2EY9XYSMnzK9Hv069jYHvms3cil2KjOQ5Id2EgqRxU01VWxqRCE7a6vamg1HlW4C84nZMpBNv8BJkxoL7IjpYqZSBr7cMdFR1NPHllmVf+dJpUbHU/U8F+gMc78quVHYI3Z5TO79yBK3+L5CseUSGk7vHjm+NOAlFRddTl3qIJTmmUAFzSk0iQjDMjHws=
  - secure: HbsNCfA4kUijbTYlMTW/tWYibQpsVPTKWN79plKCUz5HIjMZCdK9onYnVe5rMgU9H8jFYsv4Dy5jq4N76JsH1geFb4bJTcj/ksPGv6/CItIzEf9UnV8NDUwTVxZeWjBkNKvMxRu92w84NKyBUoz5FuGSW/3XEBRsRbMQMQ/IP44MXM/118BOZHv6cs8xSPM1Z8OEYziOsLlNYDZZY8owJNub2k9Ezi3hsokUTQBFBK6gkzUipprJhEzJORxO3oJoHgex5d51Rop72QWRffeAszMOaMnffi4NB2/cupJVDHIeooWy3q5r8pofYwMoklacKnx4NVvJrqY/W4Sv+SFqc/UGfxlAjrZCMfogZPmlLfgNFTHrLcNowDbcjWohl4+J8v8sf0VYejdpCb46GPF/WiFMt1aGzv8rW4QuMhlFbcj7x+DRVZAbjyU966rrohN+FTWPjETnbH6tMMm/MSmgvQkVYTWgPPQOaWO2MDuQ5KEqAjB3MPaFkg65Geq5rBwH456WA5FFPOYfYV84c728bPYAxym4IhShAB7FbfKsnjBvjjBtp57HQLsR/LRU6h8fd8BlpEOT1NlB+uOemKCbtrImUG70paqGHyGLNxKtbnoS9SWXa31Bgvf98qMtX484DKetpXAp8mtwbNR4bpvLVlE5TsiovrcVZJ+PAUOn1/g=
